### ISSUE TITLE
Openssl Configuration with Rasbperry pi

### ISSUE THREAD

**Issue by xzsfd2457** [Infineon/mbedtls-optiga-trust-x#1]
I add the three files in raspberry pi same as a procedure but it gets an error...
Can't open server.pem for reading, No such file or directory
1995427840:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:74:fopen('server.pem','r')
1995427840:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:81:
unable to load server certificate private key file

**Comment by ayushev** [comment]
Please provide a command line you use to invoke the openssl.
Ideally the output of the "ls" command as well from the place where you call the openssl

**Comment by xzsfd2457** [comment]
Terminal Commands I did


pi@raspberrypi:~/drone $  openssl s_server -tls1_2 -cipher ECDHE-ECDSA-AES128-CCM8 -accept 50000 \
> cert OPTIGA_Trust_X_InfineonTestServer_EndEntity.pem \
> key OPTIGA_Trust_X_InfineonTestServer_EndEntity_Key.pem \
> CAfile OPTIGA_Trust_X_trusted_CAs.pem \
> Verify 1 -verify_return_error -debug -state

Can't open server.pem for reading, No such file or directory
1995984896:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:74:fopen('server.pem','r')
1995984896:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:81:
unable to load server certificate private key file
pi@raspberrypi:~/drone $

**Comment by ayushev** [comment]
Please ensure, whether the commands entered correctly should be like this

openssl s_server -tls1_2 -cipher ECDHE-ECDSA-AES128-CCM8 -accept 50000 -cert OPTIGA_Trust_X_InfineonTestServer_EndEntity.pem -key OPTIGA_Trust_X_InfineonTestServer_EndEntity_Key.pem -CAfile OPTIGA_Trust_X_trusted_CAs.pem -Verify 1 -verify_return_error -debug -state

In the Wiki it is described with "\\"

pi@raspberrypi:~/certs $ openssl s_server -tls1_2 -cipher ECDHE-ECDSA-AES128-CCM8 -accept 50000 **\\**
-cert OPTIGA_Trust_X_InfineonTestServer_EndEntity.pem **\\**
-key OPTIGA_Trust_X_InfineonTestServer_EndEntity_Key.pem **\\**
-CAfile OPTIGA_Trust_X_trusted_CAs.pem **\\**
-Verify 1 -verify_return_error -debug -state

The certificate files should be in the same directory your run the openssl server

**Comment by xzsfd2457** [comment]
ss it is correct

**Comment by xzsfd2457** [comment]
openssl s_server -tls1_2 -cipher ECDHE-ECDSA-AES128-CCM8 -accept 50000 -cert ??

**Comment by xzsfd2457** [comment]
wait I will check it..

**Comment by xzsfd2457** [comment]
I didn't get please help me....

**Comment by ayushev** [comment]
Does the openssl show the same problem?

can you past here 
1) The output of the Command "ls -la"
2) exactly one-to-one the command line you use to invoke openssl

**Comment by xzsfd2457** [comment]
pi@raspberrypi:~/drone $ openssl s_server -tls1_2 -cipher ECDHE-ECDSA-AES128-CCM8 -accept 50000 

Can't open server.pem for reading, No such file or directory
1996328960:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:74:fopen('server.pem','r')
1996328960:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:81:
unable to load server certificate private key file

**Comment by ayushev** [comment]
you need to provide other parameters as well these are:
1) -cert
2) -key
3) -CAfile
and others as in the example

openssl s_server -tls1_2 -cipher ECDHE-ECDSA-AES128-CCM8 -accept 50000 \
-cert OPTIGA_Trust_X_InfineonTestServer_EndEntity.pem \
-key OPTIGA_Trust_X_InfineonTestServer_EndEntity_Key.pem \
-CAfile OPTIGA_Trust_X_trusted_CAs.pem \
-Verify 1 -verify_return_error -debug -state

**Comment by xzsfd2457** [comment]
what it mean??
pi@raspberrypi:~/drone $ openssl s_server -tls1_2 -cipher ECDHE-ECDSA-AES128-CCM8 -accept 50000 -cert OPTIGA_Trust_X_InfineonTestServer_EndEntity.pem -key OPTIGA_Trust_X_InfineonTestServer_EndEntity_Key.pem -CAfile OPTIGA_Trust_X_trusted_CAs.pem -Verify 1 -verify_return_error -debug -state
verify depth is 1, must return a certificate
Using default temp DH parameters
ACCEPT

**Comment by ayushev** [comment]
It means that you server has been launched and it expects client connections.
Prepare your ESP32 client based setup to test the connection

Don't forget about the proper WiFi setup on both RaspberryPi and ESP32

**Comment by xzsfd2457** [comment]
Thank you ayushev

**Comment by xzsfd2457** [comment]
Next, what can I do?? help  me

**Comment by ayushev** [comment]
Sorry, you need to describe your problem and things you have done more precisely. Otherwise I can't help as I don#t know what is the problem.
You can open a new issue if the new problem isn't related to the openssl configuration

**Comment by xzsfd2457** [comment]
ok

**Comment by SERIDJ** [comment]
@xzsfd2457  @ayushev  hi, 

i can send data from ESP32 to Raspberry using  x.509 client certificates  with WiFiClientSecure ?

**Comment by ayushev** [comment]
@SERIDJ hi, are you referring to the Arduino library?

**Comment by SERIDJ** [comment]
hir, @ayushev 

yes : https://github.com/espressif/arduino-esp32/tree/master/libraries/WiFiClientSecure
