### ISSUE TITLE
How to configure a OPTIGA Trust X with ESP8266 (client)

### ISSUE THREAD

**Issue by xzsfd2457** [Infineon/mbedtls-optiga-trust-x#2]

**Comment by ayushev** [comment]
https://github.com/Infineon/mbedtls-optiga-trust-x/wiki#setting_up_tls_client
But you need ESP32 not ESP8266

**Comment by xzsfd2457** [comment]
I didn't understand that give me Procedures for that...

**Comment by xzsfd2457** [comment]
just give procedure??
