### ISSUE TITLE
Mutual Authentication with MBEDTLS

### ISSUE THREAD

**Issue by ghost** [Infineon/mbedtls-optiga-trust-x#6]
Hi,

Is it possible to perform mutual authentication with the Trust X on mbedtls, with the certificate and private key loaded into the trust X? I'm unsure since as far as I know the process would involve exposing the private key to mbedtls for the signing of the certificate when it's used to authenticate the client. Any help is appreciated.

Thanks,

**Comment by ayushev** [comment]
Hello @EnkyuuBi ,

yes that would be possible

**Comment by ghost** [comment]
Thanks @ayushev 

That's good to know, are there any guides that I can refer to to implement the functionality? Thanks again for the help.

**Comment by ayushev** [comment]
the mbedtls works with OPTIGA already in the way you said, by letting the crypolibrary to build up a TLS connection (prepare and send mesages, do some intermediate crpypto etc) and OPTIGA does only the most roublesome parts, like a signature generation and ECDH
More on technical implementation can be found in the wiki section of this repo https://github.com/Infineon/mbedtls-optiga-trust-x/wiki#how-we-use-optiga-trust-x-with-mbedtls   
Also you can refer to the figure [here](https://github.com/Infineon/mbedtls-optiga-trust-m#quickstart)

**Comment by ghost** [comment]
Does this mean that for mutual authentication the certificate and private key are not exposed to Mbedtls?

**Comment by ayushev** [comment]
The certificate contains only public data and read out during the mbedtls initialization ([here](https://github.com/Infineon/mbedtls-optiga-trust-x/blob/master/main/main.c#L369) and [here](https://github.com/Infineon/mbedtls-optiga-trust-x/blob/master/main/main.c#L198)), the private key isn't exposed and used on-demand when it's needed over the optiga_crypt_ecdsa_sign() function [here](https://github.com/Infineon/optiga-trust-x/blob/5d53951ee9e65853bb38c23491dd0c79fc4e2921/examples/mbedtls_port/trustx_ecdsa.c#L44)

**Comment by ghost** [comment]
Understood, thank you very much! That clears up most of my questions.

One side question: is there any documentation for using the Trust X with MBEDTLS' psa API?

**Comment by ayushev** [comment]
Unfortunately there is no mbedtls PSA API available for OPTIGA Trust X

**Comment by ghost** [comment]
Understood, thanks!
That's all the question I have.
